- .github/workflows/tox.yml
Borrowed from [riotgen](https://github.com/aabadie/riot-generator/blob/master/.github/workflows/continuous-integration.yml#L67-L76) ;-)
> gh-actions: publish to pypi on tag creation

- .github/workflows/tox.yml
See https://github.com/pypa/gh-action-pypi-publish#customizing-target-package-dists-directory.
This worked also for the first publish of https://pypi.org/project/riotctrl/
> gh-actions: fix dist target dir

- riotctrl/ctrl.py
Same as https://github.com/RIOT-OS/RIOT/pull/14459, just for this repository. `tox` should still pass, as it is using `make` to access the mock applications.
> ctrl: get make command from environment

- riotctrl/__init__.py
- riotctrl/shell.py
- riotctrl/tests/shell_test.py
When resetting the terminal mid-test (which might be necessary e.g. if the connection is lost or other use-cases), the `replwrap` does not notice that. This ensures that it is.
I provided a test case that shows this error. With the second commit it should succeed in the CI.
> riotctrl.shell: restore terminal after reset

- .github/workflows/tox.yml
- tox.ini
Same as with https://github.com/RIOT-OS/Release-Specs/pull/200. The `tox-gh-actions` plugin is broken, so let's not use it.
> gh-actions: do not use tox-gh-actions plugin

- .github/workflows/tox.yml
The new build matrix element introduced in #8 causes the Github Action to try to publish the package twice. This makes the second run [fail with a 400 Bad Request in the publish step](https://github.com/RIOT-OS/riotctrl/runs/1748060329?check_suite_focus=true#step:7:22). This restricts the publishing just to the `test` build martrix element
> gh-actions: fix publishing

- riotctrl/__init__.py
- setup.cfg
I accidentally pushed a scope reduction of the tests (to locally speed up testing) that never were supposed to be pushed and slipped through the review. This removes that and bumps the version for this bug fix.
> tests: remove accidentally pushed scope reduction

- .github/workflows/tox.yml
- setup.py
- tox.ini
Python 3.5 reached EOL with the release of [Python 3.5.10], so we should drop support for it for the next release of `riotctrl` as well.
[Python 3.5.10]: https://www.python.org/downloads/release/python-3510/
> riotctrl: drop python 3.5 testing

- riotctrl/__init__.py
- setup.py
- tox.ini
When I tried to use our shiny new RapidJSON class, I was surprised that `pip install riotctrl[rapidjson]` doesn't install rapidjson :(. This fixes that.
> Fix and correctly test rapidjson dependency

- setup.py
We are using `replwrap` with `async_` which was [introduced in pexpect 4.7][1]. Fixes #7.
[1]: https://github.com/pexpect/pexpect/commit/e4732bd0f76936ac26884dada3f83046b2d6e72a
> pexpect: set minimum version

- riotctrl/__init__.py
- riotctrl/ctrl.py
- riotctrl/tests/utils/application/Makefile
Most test environments require `make cleanterm` to be used. This allows for that to be configurable (and defaults to that option).
> riotctrl.ctrl: make `start_term` targets configurable and default it to `make cleanterm`

- .github/workflows/tox.yml
- riotctrl/__init__.py
- setup.py
- tox.ini
This reverts #10.
Sadly, some of our test environment still runs on Python 3.5, so we need to revert this for now.
> Revert "riotctrl: drop python 3.5 testing" 

- riotctrl/shell/__init__.py
- riotctrl/tests/shell_test.py
- riotctrl/tests/utils/application/shell.py
This
- adds an initialization parameter to change the prompt
- makes the timeout to wait for the initial prompt configurable
This should fix the issues with the ESP32s in the CI, I faced in https://github.com/RIOT-OS/RIOT/pull/15951
> riotctrl.shell: add capabilities for configuration

- riotctrl/ctrl.py
- riotctrl/tests/ctrl_test.py
This moves the factory from https://github.com/RIOT-OS/RIOT/pull/15978 to `riotctrl` itself.
> riotctrl.ctrl: provide abstract factory and factory for BOARD env

- riotctrl/__init__.py
As #19 got merged before I was able to bump the version for publication, here is said bump. #19 was an API amendment, so this justifies a minor version bump.
> riotctrl: bump version to v0.4.0

- riotctrl/__init__.py
- riotctrl/shell/__init__.py
For some boards there is a weird syncing error happening: The output of a command issued via a ShellInteraction comes after the next command command issued. Examples of this can be seen in [this action](https://github.com/RIOT-OS/RIOT/runs/2004639066?check_suite_focus=true) or [in this comment](https://github.com/RIOT-OS/RIOT/pull/16111#issuecomment-788857286). With flushing pexpected completely before the prompt, this does not happen again. Thanks @fjmolinas for the hint!
For testing the tests here should pass, as well as `tests/congure_test` in RIOT on the boards we found the issue for; namely `nucleo-f411re`, `b-l072z-lrwan1`, and `b-l475e-iot01a`:
```console
$ git fetch upstream refs/pull/21/head # assuming you are in the riotctrl repo and RIOT-OS/riotctrl remote is called upstream
$ …
```
> riotctrl.shell: flush pexpect before prompt

- riotctrl/ctrl.py
- riotctrl/tests/ctrl_test.py
This adds a `flash` method for RIOTCtrl. The idea is, that with https://github.com/RIOT-OS/riotctrl/pull/13 an inherited class can easily override it, that e.g. with `iotlabcli` it only has to be called once for all nodes.
> riotctrl.ctrl: add flash method for RIOTCtrl

- riotctrl/__init__.py
- setup.cfg
~~As with other places where we use `pylint` to lint our code: it is now complaining about the non-usage of f-strings. This fixes that (luckily this time it is small).~~ Told pylint to ignore the warning instead, as we still need python 3.5 support (see https://github.com/RIOT-OS/riotctrl/pull/24#issuecomment-923802382).
In addition, I added a version bump. It's about time for a new version: last one was in March, `riotctrl.flash()` was introduced since then and the README heavily amended (which will show up on pypi as the package description).
> setup.cfg: ignore consider-using-f-string for now

- riotctrl/__init__.py
Sadly, even though the build failed, the v0.5.0 release [went somehow through to pypi](https://pypi.org/project/riotctrl/0.5.0/). So let's just keep it and fix the bug in the tests ASAP so we can progress to 0.5.1 (which we would need to do anyway, even if we delete the release on pypi. The commit is the same as it used to be in master, so please let's keep things simple and merge it as is.
> riotctrl: bump version to v0.5.0

- .github/workflows/tox.yml
- setup.py
- tox.ini
As described [here](https://packaging.python.org/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup), using twine it's possible to validate the rST Markup language of the README.
This PR adds a new command that does that to the Tox lint testenv.
This is based on #25
> Add README.rst validation to the lint testenv

- .github/workflows/tox.yml
- riotctrl/__init__.py
- riotctrl/ctrl.py
- riotctrl/shell/__init__.py
- riotctrl/shell/json.py
- riotctrl/tests/ctrl_test.py
- riotctrl/tests/riotctrl_test.py
- riotctrl/tests/shell_json_test.py
- riotctrl/tests/shell_test.py
- riotctrl/tests/utils/application/create_file.py
- riotctrl/tests/utils/application/ctrl.py
- riotctrl/tests/utils/application/echo.py
- riotctrl/tests/utils/application/hello.py
- riotctrl/tests/utils/application/shell.py
- riotctrl/tests/utils/application/sigkill_script.py
- setup.cfg
- setup.py
- tox.ini
This PR integrate the use of the [black](https://black.readthedocs.io/en/stable/) code formatter in the CI checks (tox env + gh actions).
All changes requested by black are applied in a single extra commit (using `black .` locally).
This PR is based on #26 (and #25 indirectly)
> Add support for black code formatter

- README.rst
When I tried to follow the example I found some issues
- `native` has no `flash` function
- it's `Ifconfig` not `ifconfig`
- the ping command misses closing parens
> README.rst: fix syntax errors

- .github/workflows/tox.yml
- riotctrl/ctrl.py
- riotctrl/tests/ctrl_test.py
- riotctrl/tests/riotctrl_test.py
- setup.cfg
- tox.ini
The build of #33 shows problems with the python versions used for testing. According to the error message, the available ones are listed [here](https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json). This updates the CI file to use the newest patch versions of all the tested versions.
> ci: use available python versions

- riotctrl/ctrl.py
When `stop_term` is called, `term` is not set to `None`. This breaks the check of `check_term`, as it tries to continue on using the file descriptor which is no longer valid.
> ctrl: set term to `None` when stopped

- riotctrl/shell/__init__.py
As the title indicates: we should reset the flag when manually stopping the terminal.
> shell: reset term flag when stopping term

- riotctrl/ctrl.py
- setup.cfg
The native platform on RIOT spawns two processes instead of one, so that sending the termination signal to just one process might leave a stray process open. This causes a PTY leak and eventually breaks the CI servers.
With the current `master`:
```
cbuec@W11nMate:~/RIOTstuff/riot-vanilla/RIOT$ make -C tests/turo all test && ps -A | grep -i turo
make: Entering directory '/home/cbuec/RIOTstuff/riot-vanilla/RIOT/tests/turo'
using BOARD="native64" as "native" on a 64-bit system
Building application "tests_turo" for "native64" with CPU "native".
"make" -C /home/cbuec/RIOTstuff/riot-vanilla/RIOT/boards
...
"make" -C /home/cbuec/RIOTstuff/riot-vanilla/RIOT/sys/tsrb
text    data     bss     dec     hex filename
40572    1368   59200  101140   18b14 …
```
> ctrl: send termination signals to the process group

- riotctrl/__init__.py
After the merge of #37, the version has to be increased before the release.
> riotctrl: bump version to 0.5.1

- .github/workflows/tox.yml
- setup.cfg
- tox.ini
Unfortunately the fix introduced in https://github.com/RIOT-OS/riotctrl/commit/5e679ed3446c492eead15ecd1179b0061b41c9a3 caused an issue with the earlier pylint versions that somehow did not get caught by the workflow.
Therefore, this PR introduces a more stable fix that adds a condition for newer and older python versions.
Also I added more Python versions to the `tox.ini` file to cover version 3.12 that is tested in the Workflows as well (and I have 3.10 locally, which was not covered either).
> workflows,tox: add more python versions, fix `too-many-positional-arguments` warning for all versions

- .github/workflows/tox.yml
The original PR #39 got broken somehow, GitHub seems to be stuck here:
> workflows: change to release/v1 from unsupported master

- .github/workflows/tox.yml
The suspected issue from #41 was not the cause for the PyPi failure. Instead, the output directory got changed in https://github.com/RIOT-OS/riotctrl/pull/34/commits/2e698dee414e7b3f4ebc6e488d49f62c62191d21#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449R54, which changed the path of the `dist` folder as well. The workflow was not changed, therefore the directory could not be found.
This also fixes a warning about the deprecated `packages_dir` variable.
> workflows: fix package directory
